### ISSUE TITLE
Tracking: rename project and move to colmena org

### ISSUE THREAD

**Issue by beeman** [colmena/colmena-cms#205]
- [x] Add Contributors file
- [x] Add Code of Conduct
- [x] Add https://github.com/kentcdodds/all-contributors
- [x] Rename branch `master` (`v0.x.x`) to `loopback-angular-admin`  
- [x] Rename branch `colmena-cms` (`v1.0.0`) to `master`
- [x] Rename project from `loopback-angular-admin` to `colmena-cms`
- [x] Move project from user `beeman` to org `colmena` 
- [x] Add branch `develop` and set to default
